import type Stripe from 'stripe';
import type { MembershipPlan, CoachingPlan } from '@/types';

/**
 * Permanent Stripe Products for the things this app sells.
 *
 * Prices stay where they are — every checkout still sends the amount inline,
 * so an admin changes a price in the admin panel and nothing has to be synced
 * to Stripe. Only the PRODUCT the price hangs off becomes permanent.
 *
 * Why that matters. A Checkout Session line item may describe its product
 * inline, and doing so makes Stripe mint a brand new throwaway Product for
 * that one session. Every purchase attempt therefore created another "Conquer"
 * in the product catalogue, none of them carrying a price, and nothing in
 * Stripe could tell you that they were all the same plan. Three consequences:
 *
 *  - A coupon cannot be limited to one plan, because "one plan" is not a thing
 *    that exists in Stripe to point a coupon at.
 *  - A coupon cannot skip the trial fee, for the same reason.
 *  - Revenue cannot be read per product, and the catalogue grows without end.
 *
 * The id is DERIVED from the app's own id rather than generated by Stripe and
 * cached back into Firestore. A create-then-cache approach has a check-then-act
 * race: two checkouts for the same plan at the same moment both read "no id
 * cached yet" and each create their own product, which is the exact problem
 * this is here to fix. A derived id cannot race — creating the same id twice
 * simply fails, and that failure is treated as success.
 *
 * This logic began life inside the plan-switching route, which needed it first
 * because a subscription item, unlike a checkout line item, has never accepted
 * an inline product. It lives here now so that switching a plan and buying it
 * resolve to the same product rather than two that merely share a name.
 */

/** Stripe ids must be ASCII and at most 255 characters. */
function safeId(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 255);
}

export function planProductId(planId: string): string {
  return safeId(`warfarefitness_plan_${planId}`);
}

export function programProductId(programId: string): string {
  return safeId(`warfarefitness_program_${programId}`);
}

export function coachingProductId(planId: string): string {
  return safeId(`warfarefitness_coaching_${planId}`);
}

/**
 * The paid trial's one-off access fee, kept as its own product per plan.
 *
 * Separate from the plan product on purpose. It is what lets a coupon apply to
 * the plan and not to the trial fee, which is the difference between a member
 * getting a quarter off thirty dollars and a quarter off one dollar.
 */
export function trialFeeProductId(planId: string): string {
  return safeId(`warfarefitness_trialfee_${planId}`);
}

/**
 * Returns the id of a product with this exact id, creating it if needed.
 *
 * Never throws for a reason a caller can do anything about: a lost create race
 * resolves to the winner's product. Genuine failures (bad credentials, Stripe
 * down) do throw, and every caller here treats that as "fall back to an inline
 * product" rather than failing the sale.
 */
export async function getOrCreateProduct(stripe: Stripe, id: string, name: string): Promise<string> {
  const existing = await stripe.products.retrieve(id).catch(() => null);

  if (existing) {
    // The id is derived, so a plan renamed or deactivated in the admin panel
    // after its product was created would otherwise keep the stale name on
    // every future invoice and in the billing portal forever. An archived
    // product cannot be referenced by a price at all, so it is revived here
    // rather than left to fail the next checkout.
    if (!existing.active || existing.name !== name) {
      await stripe.products.update(id, { active: true, name });
    }
    return id;
  }

  try {
    const created = await stripe.products.create({ id, name });
    return created.id;
  } catch (err) {
    // Lost a race with a concurrent request for the same product. The other
    // one now exists under this id, so reuse it instead of failing.
    const raced = await stripe.products.retrieve(id).catch(() => null);
    if (raced) return raced.id;
    throw err;
  }
}

export function getOrCreatePlanProduct(stripe: Stripe, plan: MembershipPlan): Promise<string> {
  // Deliberately the plan's name alone, with no billing term appended. One
  // plan is one product across every term, which is what makes a per-plan
  // coupon possible, and Stripe already prints the cadence beside the line
  // ("every 3 months") so the term is not lost. This also matches what plan
  // switching has always shown.
  return getOrCreateProduct(stripe, planProductId(plan.id), plan.name);
}

/** A one-off program purchase. `name` is passed rather than a Program type because the route only has the fields it read. */
export function getOrCreateProgramProduct(stripe: Stripe, programId: string, name: string): Promise<string> {
  return getOrCreateProduct(stripe, programProductId(programId), name);
}

export function getOrCreateCoachingProduct(stripe: Stripe, plan: CoachingPlan): Promise<string> {
  return getOrCreateProduct(stripe, coachingProductId(plan.id), plan.name);
}

export function getOrCreateTrialFeeProduct(stripe: Stripe, plan: MembershipPlan): Promise<string> {
  // Named for the plan it grants access to, because it appears on the member's
  // receipt beside that plan and "Trial Access Fee" on its own would not say
  // a trial of what.
  return getOrCreateProduct(stripe, trialFeeProductId(plan.id), `${plan.name} — Trial Access Fee (one-time)`);
}
